### ISSUE TITLE
Feil lenker i README.md

### ISSUE THREAD

**Issue by njanor** [andreasBerre/monsterbutikken#7]
I README.md er det lenka til https://github.com/andreasBerre/monstershopen for Java-versjonen og https://github.com/oven/monstershopen.net for C# versjonen.

Antar det her er snakk om https://github.com/andreasBerre/monsterbutikken for Java og https://github.com/oven/monsterbutikken.net for C#.

**Comment by Andersos** [comment]
Denne kan vel lukkes?
